---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.7-bookworm

inputs:
  - name: dp-integrity-checker

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-integrity-checker/ci/scripts/build.sh
